[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "python-socket-message"
version = "1.0.0"
description = "Python Socket Message"

[tools.setuptools.packages.find]
where = ["src"]